# .sops.yaml

keys:
  - &maranello age1ksrxfhh58az67e2lzssjqqae5vs43uexc5r6js38eywc4yu8tfmsrmdjsp
  - &daytona age1fvs6tt5e2exjxdara9wweukzk47q8n83n0alaljudyjtjnende6s5nyzfx
  - &acarshub age1rlew25xc7psxfwgwahn2zdc67gxd3vmkymy58gfe8gx90zuh34aqlalkxm
  - &hfdlhub1 age1c6qkqvcwggg4wekk2e02utfgevpw8kdul0r5ddq5nfg4gckzcapsxzqapd
  - &hfdlhub2 age1z36t4m08swfyp9emazxywz7l8dtxx2h9rfrlln3eqyqsyaqjvfwqw96d87
  - &sdrhub age1utqkfpf5pjul0hlkuple53f5c0unaw8dr2ud76fyt0mwh4kr3u5qg3hufh
  - &vdlmhub age133nrgx868zl7p39hahs92cs86weswsna5zynnvxmnerfjdvrq5eqankymd
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *maranello
          - *daytona
          - *acarshub
          - *hfdlhub1
          - *hfdlhub2
          - *sdrhub
          - *vdlmhub
