gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a6d189"
      - bold
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#a6d189"
    defaultFgColor:
      - "#c6d0f5"
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    searchingActiveBorderColor:
      - "#e5c890"
    selectedLineBgColor:
      - "#414559"
    unstagedChangesColor:
      - "#e78284"

  authorColors:
    "*": "#b4befe"
    "Fred Clausen": "#ffa500"
    "github[bot]": "#800080"
