---
- name: Update NixOS Systems
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: nixos
  tasks:
    - name: Update nixos source
      become: no
      git:
        repo: https://github.com/fredclausen/nixos.git
        dest: /home/fred/GitHub/nixos
        version: main
        update: yes
        clone: no
        force: no
      register: git_result
    - name: Update system if repo is changed
      become: yes
      command: nixos-rebuild switch --flake .#{{ hostvars[inventory_hostname]['vars']['nix_name'] }}
      args:
        chdir: /home/fred/GitHub/nixos
      when: git_result.changed

- name: Update Ubuntu Systems
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: ubuntu
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      become: yes
      apt:
        upgrade: dist
    - name: check if reboot is needed
      stat:
        path: /var/run/reboot-required
      register: check_reboot
    - meta: end_host
      when: not check_reboot.stat.exists
    - name: System needs reboot
      debug:
        msg: "System needs reboot"
      when: check_reboot.stat.exists
