{
 "title": "Ultrafeeder Stats",
 "description": "ADSB/UAT statistics from Ultrafeeder",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "ADSB Performance Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Tracked Aircraft",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(readsb_aircraft_total{job=\"ultrafeeder\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Maximum Range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readsb_distance_max{job=\"ultrafeeder\"} * 0.000539957",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. SNR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readsb_aircraft_rssi_average{job=\"ultrafeeder\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "readsb_local_noise{job=\"ultrafeeder\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aircraft Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "readsb_aircraft_total{job=\"ultrafeeder\"}",
     "legendFormat": "total"
    },
    {
     "expr": "readsb_aircraft_adsb_icao{job=\"ultrafeeder\"}",
     "legendFormat": "ADS-B"
    },
    {
     "expr": "readsb_aircraft_mlat{job=\"ultrafeeder\"}",
     "legendFormat": "MLAT"
    },
    {
     "expr": "readsb_aircraft_mode_ac{job=\"ultrafeeder\"}",
     "legendFormat": "Mode-A/C"
    },
    {
     "expr": "readsb_aircraft_tisb_icao{job=\"ultrafeeder\"}",
     "legendFormat": "TIS-B"
    },
    {
     "expr": "readsb_aircraft_adsr_icao{job=\"ultrafeeder\"}",
     "legendFormat": "ADS-R"
    },
    {
     "expr": "readsb_aircraft_adsc{job=\"ultrafeeder\"}",
     "legendFormat": "ADS-C"
    }
   ]
  },
  {
   "title": "Max - Min Range",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "readsb_distance_max{job=\"ultrafeeder\"} * 0.000539957",
     "legendFormat": "max range (nm)"
    },
    {
     "expr": "readsb_distance_min{job=\"ultrafeeder\"} * 0.000539957",
     "legendFormat": "min range (nm)"
    }
   ]
  },
  {
   "title": "Top Aircraft Models",
   "type": "timeseries",
   "description": "Aircraft models with most messages received",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk by(t) (10, count by(t) (readsb_aircraft_seen{job=\"ultrafeeder\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(readsb_messages{job=\"ultrafeeder\"})",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "readsb_local_strong_signals{job=\"ultrafeeder\"}",
     "legendFormat": "Messages > 3dbFS"
    },
    {
     "expr": "max(readsb_cpr_local_ok{job=\"ultrafeeder\"}) / 60",
     "legendFormat": "Positions/s "
    }
   ]
  },
  {
   "title": "Positions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(readsb_position_count_total{job=\"ultrafeeder\"})",
     "legendFormat": "ADS-B"
    }
   ]
  },
  {
   "title": "Tracks Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(readsb_tracks_all{job=\"ultrafeeder\"})",
     "legendFormat": "Tracks"
    },
    {
     "expr": "max(readsb_tracks_single_message{job=\"ultrafeeder\"})",
     "legendFormat": "Tracks with single message"
    }
   ]
  },
  {
   "title": "Signal Strength ADS-B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "readsb_aircraft_rssi_max{job=\"ultrafeeder\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": "readsb_aircraft_rssi_min{job=\"ultrafeeder\"}",
     "legendFormat": "Min signal"
    },
    {
     "expr": "readsb_aircraft_rssi_median{job=\"ultrafeeder\"}",
     "legendFormat": "Median"
    },
    {
     "expr": "readsb_aircraft_rssi_quart1{job=\"ultrafeeder\"}",
     "legendFormat": "1st quartile"
    },
    {
     "expr": "readsb_aircraft_rssi_quart3{job=\"ultrafeeder\"}",
     "legendFormat": "3rd quartil"
    }
   ]
  },
  {
   "title": "readsb CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(readsb_cpu_reader{job=\"ultrafeeder\"}) / 60000",
     "legendFormat": "SDR Reader"
    },
    {
     "expr": "max(readsb_cpu_demod{job=\"ultrafeeder\"}) / 60000",
     "legendFormat": "Demodulator"
    },
    {
     "expr": "max(readsb_cpu_background{job=\"ultrafeeder\"}) / 60000",
     "legendFormat": "Background"
    }
   ]
  },
  {
   "title": "SDR Gain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "readsb_sdr_gain{job=\"ultrafeeder\"}",
     "legendFormat": "SDR gain (dB)"
    }
   ]
  },
  {
   "title": "SDR PPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "readsb_demod_estimated_ppm{job=\"ultrafeeder\"}",
     "legendFormat": "SDR freq drift (ppm)"
    },
    {
     "expr": "avg_over_time(readsb_demod_estimated_ppm{job=\"ultrafeeder\"}[15m])",
     "legendFormat": "15 min avg"
    }
   ]
  },
  {
   "title": "ADSB List of Aircrafts",
   "type": "table",
   "description": "Aircraft list",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "count by(flight, t, r, nav_modes) (readsb_aircraft_seen{job=\"ultrafeeder\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UAT Performance Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 } },
  { "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "ADSB/UAT Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tar1090 Stats",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 79 },
     "options": {
      "content": "\n\n<iframe src=\"http://feeder_url/graphs1090\" title=\"Stats\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>"
     }
    },
    {
     "title": "Traffic Heatmap",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 99 },
     "options": {
      "content": "\n\n<iframe src=\"http://feeder_url?heatmap&realheat&hideSidebar&hideButtons&centerReceiver&zoom=7\" title=\"Heat Map\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>"
     }
    },
    {
     "title": "UAT Traffic",
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 119 },
     "options": {
      "content": "\n<!-- replace http://feeder_url:30980/skyaware978/ with the URL of your skyaware978 map -->\n<iframe src=\"http://feeder_url:30980/skyaware978/\" title=\"SkyAware978\" style=\"width:100%; height:100%; padding:0; margin:0; border:none;\"></iframe>"
     }
    }
   ]
  }
 ]
}