name: update-flakes-darwin
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# https://github.com/bbigras/nix-config

jobs:
  get-flake-inputs:
    runs-on: macos-latest
    outputs:
      flake-inputs: ${{ steps.get-flake-inputs.outputs.flake-inputs }}
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          sparse-checkout: macflake/flake.lock
      - id: get-flake-inputs
        run: |
          flake_inputs="$(jq -c '.nodes.root.inputs | {flake: keys}' macflake/flake.lock)"
          echo "flake-inputs=${flake_inputs}" >> "$GITHUB_OUTPUT"
  update-flake:
    name: update-${{ matrix.flake }}
    runs-on: macos-latest
    needs: get-flake-inputs
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-flake-inputs.outputs.flake-inputs) }}
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          extra-conf: accept-flake-config = true
      - run: git config --global user.email "noreply@github.com"
      - run: git config --global user.name "github[bot]"
      - uses: cpcloud/flake-update-action@v2.0.1
        with:
          dependency: macflake/${{ matrix.flake }}
          pull-request-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-author: github[bot] <noreply@github.com>
          delete-branch: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-branch-prefix: update-
          automerge: true
